name: Send Email on Build

on:
  push:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send Email
        uses: dawidd6/action-send-mail@v2  # Or betterfor/action-sned-mail@main
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: sumamegur@gmail.com
          password: "weob lskj pxkz bmyi" # Your SMTP password
          subject: "GitHub Actions Build Status"
          to: sumamegur@gmail.com, sumabhat993@gmail.com
          from: "GitHub Actions sumamegur@gmail.com"  # Sender email and name
          body: |
            Build completed for ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Status: ${{ job.status }}